name: Build and Release Windows EXE

on:
  push:
    tags:
    - v*

permissions:
  contents: write
  actions: write

env:
  PACKAGE_NAME: ebsco-converter

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 2.1.1

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Build EXE
      run: poetry run pyinstaller --onefile --name ${{ env.PACKAGE_NAME }} pythonexe/main.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: dist/${{ env.PACKAGE_NAME }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download EXE artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: dist/

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
        dist/${{ env.PACKAGE_NAME }}.exe \
        --title "Release ${{ github.ref_name }}"
